#!/usr/bin/env Rscript
args = commandArgs(trailingOnly=TRUE)
# test if there is at least one argument: if not, return an error
if (length(args)==0) {
  stop("At least one argument must be supplied (input file).n", call.=FALSE)
} else if (length(args)==1) {
  args[2] = "out.txt"
}

# file "Mapability_100.txt"
BALL <- read.delim(args[1], header = TRUE)

#command line running: Rscript thiscript.R Mapability_100.txt




